### ISSUE TITLE
Feature where letters disappear after set time

### ISSUE THREAD

**Issue by prefosterous** [paulfchristiano/anagrams#1]
First, thank you for making this game - I've put more hours into it than I care to admit.

I'm sure this is far from your top priorities at the moment, but I have a feature request. I'd love for there to be a "disappearing letters" mode. The user enters in a decimal number specifying the number of seconds that the letters should stay visible, and after that time, they disappear. From that point on, both the scrambled letters, and any letters you type, would not be visible. Gameplay is otherwise unchanged: smaller words still appear when correctly typed and entered, and the round still ends when the full word is entered or when time runs out. It's kind of challenge mode: how briefly can the letters flash on the screen before it becomes impossible to get the full word?

Do you accept pull requests? I or one of my friends would probably be willing to code this up if we could get it included in the game.

**Comment by paulfchristiano** [comment]
I'd accept a PR. This should be very straightforward. Would prefer it as a new line on options.

My default would be to have radio buttons for like 5 options but I'd be happy with having text input as well if you prefer that.

**Comment by prefosterous** [comment]
That's great to hear. Talking with some friends now about getting it made. Radio buttons make sense. We'll playtest some different times (offhand I was thinking something like 0.1, 0.2, 0.5, 1, and 5s, but we'll see)

**Comment by prefosterous** [comment]
I see the feature got merged in, thanks for accepting the PR. Right now it's not showing up on the live site, does something else have to happen before it becomes playable?

**Comment by prefosterous** [comment]
I see it's live now. Thanks again! It's a underrated game, I'll continue to evangelize it.

**Comment by paulfchristiano** [comment]
Build failed for some reason, no idea why, I reran it and it's live now.
